Models/UserProject.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeeklyProgram.Models
{
    public class UserProject
    {
        [Key]
        public Guid Id { get; set; }
        public string? UserId { get; set; }
        [ForeignKey("Template")]
        public Guid? TemplateId { get; set; }
        
        public Template? Template { get; set; }
        [Display(Name ="اسم المشروع")]
        public string? ProjectTitle { get; set; }
        public string? Objectstext { get; set; }
        [Display(Name ="الصورة")]
        public string? ImageUrl { get; set; }
        [Display(Name ="تاريخ الانشاء")]
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }
    }
}

Controllers/UserProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WeeklyProgram.Data;
using WeeklyProgram.Models;
using WeeklyProgram.Services;
using WeeklyProgram.ViewModel;

namespace WeeklyProgram.Controllers
{
    public class UserProjectsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly ImageService _imageService;

        public UserProjectsController(ApplicationContext context, ImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        // GET: UserProjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserProjects.ToListAsync());
        }

        // GET: UserProjects/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserProject? userProject = await _context.UserProjects.FirstOrDefaultAsync(m => m.Id == id);

            Template template = _context.Templates.Find(userProject!.TemplateId)!;

            ProjectViewModel projectViewModel = new ProjectViewModel()
            {
                TemplateId = (Guid)userProject.TemplateId!,
                Id = userProject.Id,
                ObjectJson = JsonConvert.DeserializeObject<string[]>(userProject.Objectstext!),
                ImageUrl = userProject.ImageUrl,
                Title = template.Title,
                ArrayRow = template.ArrayRow,
                ArrayColmun = template.ArrayColmun,
                Descreption = template.Descreption,
                ProjectName = userProject.ProjectTitle


            };

            if (userProject == null)
            {
                return NotFound();
            }

            return View(projectViewModel);
        }




        public IActionResult ProcessImage(Guid? id)
        {
            UserProject? userProject = _context.UserProjects.Find(id);

            Template template = _context.Templates.Find(userProject!.TemplateId)!;

            ProjectViewModel projectViewModel = new ProjectViewModel()
            {
                TemplateId = (Guid)userProject.TemplateId!,
                Id = userProject.Id,
                ObjectJson = JsonConvert.DeserializeObject<string[]>(userProject.Objectstext!),
                ImageUrl = userProject.ImageUrl,
                Title = template.Title,
                ArrayRow = template.ArrayRow,
                ArrayColmun = template.ArrayColmun,
                Descreption = template.Descreption,
                ProjectName = userProject.ProjectTitle
            };
            string servicePrinter = projectViewModel.TemplateId.ToString().ToUpper();
            if (servicePrinter == "6F203499-E35B-4198-B850-23D308626A76" ||
             servicePrinter == "594158D7-89DD-496D-8954-8E747154AAC1")
            {
                return File(_imageService.ImagePrinter(projectViewModel), "image/png");
            }
            else
            {
                throw new Exception("هذا القالب غير موجود");
            }

        }


        public IActionResult TemplateList()
        {
            var templates = _context.Templates.ToList();
            return View(templates);
        }




        // GET: UserProjects/Create
        [HttpGet]
        public IActionResult Create(Guid? id)
        {
            Template template = new Template();
            template = _context.Templates.Find(id)!;


            ProjectViewModel projectViewModel = new ProjectViewModel();

            projectViewModel.ObjectJson = JsonConvert.DeserializeObject<string[]>(template.Objectstext!);
            projectViewModel.ArrayColmun = template.ArrayColmun;
            projectViewModel.ArrayRow = template.ArrayRow;
            projectViewModel.ImageUrl = template.ImageUrl;
            projectViewModel.Descreption = template.Descreption;
            projectViewModel.Title = template.Title;



            return View(projectViewModel);
        }

        // POST: UserProjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ProjectViewModel projectViewModel)
        {
            UserProject userProject = new UserProject();
            userProject.TemplateId = projectViewModel.Id;
            userProject.CreatedDate = DateTime.Now;
            userProject.ImageUrl = projectViewModel.ImageUrl;
            userProject.ProjectTitle = projectViewModel.ProjectName;
            userProject.UserId = "1";
            userProject.Objectstext = JsonConvert.SerializeObject(projectViewModel.ObjectJson);

            if (projectViewModel is not null)
            {
                userProject.Id = Guid.NewGuid();
                _context.Add(userProject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userProject);
        }

        // GET: UserProjects/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserProject? userProject = await _context.UserProjects.FindAsync(id);
            Template template = _context.Templates.Find(userProject!.TemplateId)!;
            ProjectViewModel projectViewModel = new ProjectViewModel()
            {
                TemplateId = (Guid)userProject.TemplateId!,
                Id = userProject.Id,
                ObjectJson = JsonConvert.DeserializeObject<string[]>(userProject.Objectstext!),
                ImageUrl = userProject.ImageUrl,
                Title = template.Title,
                ArrayRow = template.ArrayRow,
                ArrayColmun = template.ArrayColmun,
                Descreption = template.Descreption,
                ProjectName = userProject.ProjectTitle,
                CurrentDate = userProject.CreatedDate

            };


            return View(projectViewModel);
        }

        // POST: UserProjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [FromForm] ProjectViewModel projectViewModel)
        {
            UserProject userProject = new UserProject()
            {
                Id = projectViewModel.Id,
                UserId = projectViewModel.UserId,
                ProjectTitle = projectViewModel.ProjectName,
                TemplateId = projectViewModel.TemplateId,
                Objectstext = JsonConvert.SerializeObject(projectViewModel.ObjectJson),
                ImageUrl = projectViewModel.ImageUrl,
                CreatedDate = projectViewModel.CurrentDate,
            };
            userProject.UserId = "1";
            if (id != userProject.Id)
            {
                return NotFound();
            }

            if (userProject.ProjectTitle is not null)
            {
                _context.UserProjects.Update(userProject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("Model","اسم المشروع ضروري");
            }
            #region 
            // if (ModelState.IsValid)
            // {
            //     try
            //     {
            //         _context.Update(userProject);
            //         await _context.SaveChangesAsync();
            //     }
            //     catch (DbUpdateConcurrencyException)
            //     {
            //         if (!UserProjectExists(userProject.Id))
            //         {
            //             return NotFound();
            //         }
            //         else
            //         {
            //             throw;
            //         }
            //     }
            //     return RedirectToAction(nameof(Index));
            // }
            #endregion
            return View(projectViewModel);
        }

        // GET: UserProjects/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProject = await _context.UserProjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProject == null)
            {
                return NotFound();
            }

            return View(userProject);
        }

        // POST: UserProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var userProject = await _context.UserProjects.FindAsync(id);
            if (userProject != null)
            {
                _context.UserProjects.Remove(userProject);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserProjectExists(Guid id)
        {
            return _context.UserProjects.Any(e => e.Id == id);
        }
    }
}

Views/UserProjects/Create.cshtml
@model ProjectViewModel

@{
    ViewData["Title"] = "Create";
}
<div>
    <br>
</div>
<h3 class="text-center">انشاء مشروع</h3>
<hr />
<div class="row">
    <div class="">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id">
            <input type="hidden" asp-for="ImageUrl">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="ProjectName" class="control-label"></label>
                        <input asp-for="ProjectName" class="form-control my-1" placeholder="اعط اسم للمشروع" required />
                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control my-1" disabled />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ArrayRow" class="control-label"></label>
                        <input asp-for="ArrayRow" class="form-control my-1" disabled />
                        <span asp-validation-for="ArrayRow" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ArrayColmun" class="control-label"></label>
                        <input asp-for="ArrayColmun" class="form-control my-1" disabled />
                        <span asp-validation-for="ArrayColmun" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descreption" class="control-label"></label>
                        <input asp-for="Descreption" class="form-control my-1" disabled />
                        <span asp-validation-for="Descreption" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <div class="text-center">
                            <img src="~/uploads/templates/@Model.ImageUrl" alt="image" class="img-thumbnail"
                                style="width:600px;" />
                        </div>
                    </div>
                </div>
                <h2 class="text-center">ادخال متغيرات القالب</h2>
                <hr>
                <div>
                    <table class="table table-hover table-dark table-striped-columns text-md-center">
                        <thead>
                            <tr>
                                        @for (int i = 0; i < Model.ArrayColmun; i++)
                                        {
                                    <th><input class="form-control" asp-for="@Model.ObjectJson![i]" type="text"></th>
                                        }
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                        @for (int i = Model.ArrayColmun; i < Model.ObjectJson.Length;)
                                        {
                                <tr>
                                                @for (int j = 0; j < Model.ArrayColmun; j++)
                                                {
                                        <td><input class="form-control" asp-for="@Model.ObjectJson[i]" type="text"></td>
                                                    i++;
                                                }
                                </tr>
                                        }
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="form-group text-center">
                    <input type="submit" value="انشاء" class="btn btn-primary" />
                    <a class="btn btn-outline-secondary" asp-action="Index">الرجوع الى القائمة</a>
                </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/UserProjects/Delete.cshtml
@model WeeklyProgram.Models.UserProject

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TemplateId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TemplateId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Objectstext)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Objectstext)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/UserProjects/Details.cshtml
@model ProjectViewModel
@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center">عرض المشروع</h1>
<hr />
<div class="row">
    <div class="">
        <form asp-controller="UserProjects" asp-action="ProcessImage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id">
            <input type="hidden" asp-for="ImageUrl">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="ProjectName" class="control-label"></label>
                        <input asp-for="ProjectName" class="form-control my-1" disabled />
                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control my-1" disabled />
                        <input type="hidden" asp-for="Title">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ArrayRow" class="control-label"></label>
                        <input asp-for="ArrayRow" class="form-control my-1" disabled />
                        <input type="hidden" asp-for="ArrayRow">
                        <span asp-validation-for="ArrayRow" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ArrayColmun" class="control-label"></label>
                        <input asp-for="ArrayColmun" class="form-control my-1" disabled />
                        <input type="hidden" asp-for="ArrayColmun">
                        <span asp-validation-for="ArrayColmun" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descreption" class="control-label"></label>
                        <input asp-for="Descreption" class="form-control my-1" disabled />
                        <span asp-validation-for="Descreption" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <div class="text-center">
                            <img src="~/uploads/templates/@Model.ImageUrl" alt="image" class="img-thumbnail"
                                style="width:600px;" />
                        </div>
                    </div>
                </div>
                <h2 class="text-center">ادخال متغيرات القالب</h2>
                <hr>
                <div>
                    <table class="table table-hover table-dark table-striped-columns text-md-center">
                        <thead>
                            <tr>
                                @for (int i = 0; i < Model.ArrayColmun; i++)
                                {
                                    <th>
                                        <input class="form-control" asp-for="@Model.ObjectJson![i]" disabled>
                                    </th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = Model.ArrayColmun; i < Model.ObjectJson!.Length;)
                            {
                                <tr>
                                    @for (int j = 0; j < Model.ArrayColmun; j++)
                                    {
                                        <td>
                                            <input class="form-control" asp-for="@Model.ObjectJson[i]" disabled>
                                        </td>
                                        i++;
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="form-group text-center">
                    
                    <a class="btn btn-info" asp-action="Index">الرجوع الى القائمة</a>
                    <a class="btn btn-outline-secondary" asp-controller="UserProjects" asp-action="ProcessImage" asp-route-id="@Model.Id">انشاء الملف <i class="fa-regular fa-image"></i></a>
                </div>
        </form>
    </div>
</div>

Views/UserProjects/Edit.cshtml
@model ProjectViewModel

@{
    ViewData["Title"] = "Edit";

}

<h4 class="text-center">تعديل المشروع</h4>
<hr />
<div class="row">
    <form asp-action="Edit" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id">
        <input type="hidden" asp-for="ImageUrl">
        <input type="hidden" asp-for="TemplateId">
        <input type="hidden" asp-for="CurrentDate">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label asp-for="ProjectName" class="control-label"></label>
                    <input asp-for="ProjectName" class="form-control my-1" placeholder="اعط اسم للمشروع" required />
                    <span asp-validation-for="ProjectName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control my-1" disabled />

                </div>
                <div class="form-group">
                    <label asp-for="ArrayRow" class="control-label"></label>
                    <input asp-for="ArrayRow" class="form-control my-1" disabled />

                </div>
                <div class="form-group">
                    <label asp-for="ArrayColmun" class="control-label"></label>
                    <input asp-for="ArrayColmun" class="form-control my-1" disabled />

                </div>
                <div class="form-group">
                    <label asp-for="Descreption" class="control-label"></label>
                    <input asp-for="Descreption" class="form-control my-1" disabled />

                </div>
            </div>

            <div class="col-6">
                <div class="form-group">
                    <div class="text-center">
                        <img src="~/uploads/templates/@Model.ImageUrl" alt="image" class="img-thumbnail"
                            style="width:600px;" />
                    </div>
                </div>
            </div>
            <h2 class="text-center">ادخال متغيرات القالب</h2>
            <hr>
            <div>
                <table class="table table-hover table-dark table-striped-columns text-md-center">
                    <thead>
                        <tr>
                            @for (int i = 0; i < Model.ArrayColmun; i++)
                            {
                                <th>
                                    <input class="form-control" asp-for="@Model.ObjectJson![i]">
                                </th>
                            }
                        </tr>
                    </thead>
                    <tbody>

                        @for (int i = Model.ArrayColmun; i < Model.ObjectJson!.Length;)
                        {
                            <tr>
                                @for (int j = 0; j < Model.ArrayColmun; j++)
                                {
                                    <td>
                                        <input class="form-control" asp-for="@Model.ObjectJson[i]" type="text">
                                    </td>
                                    i++;
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="form-group text-center">
                <input type="submit" value="حفظ" class="btn btn-primary" />
                <a class="btn btn-outline-secondary" asp-action="Index">الرجوع الى القائمة</a>
            </div>
    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/UserProjects/Index.cshtml
@model IEnumerable<WeeklyProgram.Models.UserProject>

@{
    ViewData["Title"] = "Index";
}

<h2 class="text-center">مشاريعي</h2>
<hr>

<p>
    <a class="btn btn-success" asp-controller="UserProjects" asp-action="TemplateList">انشاء مشروع</a>
</p>
<div class="table-responsive">
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
                <th>
                    <a class="btn btn-success" asp-controller="UserProjects" asp-action="TemplateList">انشاء مشروع</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProjectTitle)
                    </td>
                    <td>
                        <img class="img-fluid" src="~/uploads/templates/@item.ImageUrl" alt="image" style="width:60px" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><i
                                class="fa-solid fa-pen-to-square"></i></a> |
                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><i
                                class="fa-solid fa-circle-info"></i></a> |
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i
                                class="fa-solid fa-trash-can"></i></a> |
                        <button onclick="showImageModal('@item.Id', '@item.ProjectTitle')" class="btn btn-secondary"><i
                                class="fa-regular fa-image"></i></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body text-center">
                <img id="modalImage" class="img-fluid" src="" alt="">
            </div>
            <div class="modal-footer text-right">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">اغلاق</button>
                <button type="button" class="btn btn-primary" id="downloadButton">حفظ</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    const exampleModal = new bootstrap.Modal(document.getElementById('exampleModal'));

    async function fetchImageWithId(id) {
        try {
            const response = await fetch(`/UserProjects/ProcessImage/${id}`);
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            const blob = await response.blob();
            const imageUrl = URL.createObjectURL(blob);
            return { imageUrl, blob };
        } catch (error) {
            console.error('Error fetching image:', error);
        }
    }

    async function showImageModal(id, projectTitle) {
        try {
            const { imageUrl, blob } = await fetchImageWithId(id);
            document.getElementById('modalImage').src = imageUrl;
            document.getElementById('downloadButton').onclick = () => downloadImage(blob, projectTitle + '.png');
            exampleModal.show();
        } catch (error) {
            console.error('Error processing image:', error);
        }
    }

    function downloadImage(blob, fileName) {
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
</script>

Views/UserProjects/TemplateList.cshtml
@model IEnumerable<Template>
@{
    ViewData["Title"] = "قائمة القوالب";
}
<h2 class="text-center">قائمة القوالب</h2>
<div class="row ">
    @foreach (var item in Model)
    {

        <div class="card m-1" style="width: 15rem;">
            <img src="~/uploads/templates/@item.ImageUrl" class="card-img-top" alt="image">
            <div class="card-body justify-content-baseline">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">
                    @item.Descreption
                </p>
                <a asp-action="Create" asp-controller="UserProjects" asp-route-id="@item.Id" class="btn btn-primary">انشاء مشروع</a>
            </div>
        </div>

         
    }
</div>